owner: InstaSwitch # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

sites:
  - name: InstaSwitch Platform
    url: https://api.instaswitch.co/api_health
  - name: Landing Page
    url: https://instaswitch.co

status-website:
  cname: status.instaswitch.co
  logoUrl: https://status.instaswitch.co/instaswitch-logo.svg
  favicon: https://imagedelivery.net/j3L7QzNIlDWn3v_yG7FjGg/8036fa23-104c-4ca2-645e-8cc2e6ae1f00/public
  forceHttps: true
  baseUrl: /
  name: ""
  introTitle: "InstaSwitch System Status"
  navbar:
    - title: Status
      href: /
    - title: InstaSwitch
      href: https://instaswitch.co
    - title: Changelog
      href: https://instaswitch.github.io/public-changelog
  themeUrl: https://status.instaswitch.co/instaswitch-theme.css
