owner: InstaSwitch # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

sites:
  - name: InstaSwitch Platform
    url: https://app.instaswitch.co/health_check
  - name: Landing Page
    url: https://www.instaswitch.co

status-website:
  cname: status.instaswitch.co
  logoUrl: https://cdn.prod.website-files.com/67957401e8aee4ed4476769a/679d476c50bc595bdebcf77b_favicon.png
  favicon: https://cdn.prod.website-files.com/67957401e8aee4ed4476769a/679d476c50bc595bdebcf77b_favicon.png
  name: InstaSwitch
  introTitle: "**InstaSwitch Status** - Real-time monitoring of InstaSwitch services"
  introMessage: This page provides current operational status for all InstaSwitch services. We continuously monitor our systems and automatically update this page when issues are detected. For support inquiries, please contact our team at support@instaswitch.co.
  navbar:
    - title: Status
      href: /
    - title: InstaSwitch
      href: https://instaswitch.co
  theme: ocean
