owner: InstaSwitch # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

sites:
  - name: InstaSwitch Platform
    url: https://app.instaswitch.co/health_check
  - name: Landing Page
    url: https://www.instaswitch.co

status-website:
  cname: status.instaswitch.co
  logoUrl: https://imagedelivery.net/j3L7QzNIlDWn3v_yG7FjGg/115be7ab-a201-4976-f1e7-c82faca23000/public
  favicon: https://imagedelivery.net/j3L7QzNIlDWn3v_yG7FjGg/8036fa23-104c-4ca2-645e-8cc2e6ae1f00/public
  forceHttps: true
  baseUrl: /
  name: InstaSwitch
  introTitle: "InstaSwitch System Status"
  navbar:
    - title: Status
      href: /
    - title: InstaSwitch
      href: https://instaswitch.co
    - title: Changelog
      href: https://instaswitch.github.io/public-changelog
  themeUrl: https://status.instaswitch.co/instaswitch-theme.css
